/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.me.getphonelocation;

public final class R {
    public static final class attr {
    }
    public static final class id {
        public static final int result=0x7f040004;
        public static final int widget0=0x7f040000;
        public static final int widget33=0x7f040002;
        public static final int widget34=0x7f040003;
        public static final int yourphone=0x7f040001;
    }
    public static final class layout {
        public static final int getphone=0x7f020000;
        public static final int main=0x7f020001;
    }
    public static final class string {
        public static final int app_name=0x7f030000;
    }
}
